insert into "course" (code, name, credits, total_hours)
values ('DONNEES1', 'Bases de donnees structurees', 4, 40),
       ('DONNEES2', 'Applications a forte consommation en donnees', 5, 50),
       ('DONNEES4', 'Business Intelligence', 4, 40),
       ('IA1', 'Intelligence artificielle symbolique et statistique', 5, 50),
       ('LV1', 'Langue Vivante - Francais', 2, 20),
       ('LV2', 'Langue Vivante - Anglais', 2, 20),
       ('METIER1', 'ERP et derives', 4, 40),
       ('MGT1', 'Travail collaboratif', 3, 30),
       ('MGT2', 'Gestion de projet', 3, 30),
       ('MOB1', 'Developpement d''applications mobiles', 5, 50),
       ('PRO1', 'Vie professionnelle', 2, 20),
       ('PRO2', 'Alternance', 6, 60),
       ('PRO3', 'Entrepreneuriat', 3, 30),
       ('PRO4', 'Experience professionnelle', 6, 60),
       ('PROG1', 'Algorithmique', 6, 60),
       ('PROG2', 'Programmation orientee objet', 6, 60),
       ('PROG3', 'Implementation d''API Backend', 5, 50),
       ('PROG4', 'Qualite et surete des applications', 5, 50),
       ('PROJET1', 'Projet de specialisation', 6, 60),
       ('SECU1', 'Securite des systemes d''information', 4, 40),
       ('SECU2', 'Vulnerabilites applicatives', 4, 40),
       ('SYS1', 'Systemes d''exploitation', 4, 40),
       ('SYS2', 'Systemes interconnectes', 4, 40),
       ('SYS3', 'Applications sur le cloud', 4, 40),
       ('THEORIE1', 'Mathematiques de l''informatique', 6, 60),
       ('TN1', 'Marketing Digital', 3, 30),
       ('TN2', 'E-reputation et Blogging', 3, 30),
       ('TN3', 'Referencement web', 3, 30),
       ('TN4', 'Techniques du web avances', 4, 40),
       ('WEB1', 'Interfaces web', 5, 50),
       ('WEB2', 'Interfaces web globalement connectees', 5, 50),
       ('WEB3', 'Interfaces web globalement connectees - avance', 4, 40);
